# Numerical Programming
Experiments with the NumPy Library

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr1.ndim

1

In [10]:
arr2.ndim

2

In [11]:
arr1[2]

3

In [12]:
arr2[1, 1]

5

In [13]:
arr2.shape

(2, 3)

In [14]:
arr1.shape

(5,)

In [16]:
np.zeros((5000, 4000))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
np.ones((6, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.ones((6, 7), dtype=np.int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [19]:
np.full((6, 7), 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [20]:
np.ones((6, 7)) * 7

array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]])

In [21]:
arr3 = np.ones((3, 4))

In [24]:
arr4 = np.zeros_like(arr3)

In [25]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr5 = np.empty((12, 15))

In [29]:
arr5

array([[ 0.00000000e+000,  9.09080788e-322,  0.00000000e+000,
         6.93496754e-310,  0.00000000e+000,  0.00000000e+000,
                     nan,  0.00000000e+000,  7.92574498e-135,
         0.00000000e+000,  4.44659081e-323,  6.93496850e-310,
         6.93496104e-310,              nan,  0.00000000e+000],
       [             nan,  6.93492808e-310,  6.93489444e-310,
         3.55727265e-322,  3.45845952e-323,  6.93496850e-310,
         6.93496104e-310,  0.00000000e+000,  4.94065646e-324,
         4.94065646e-324,  6.93492808e-310,  6.93489444e-310,
         7.11454530e-322,  1.48219694e-323,  6.93496850e-310],
       [ 6.93496104e-310,  0.00000000e+000,  4.94065646e-324,
         4.94065646e-324,  4.94065646e-323,  4.94065646e-324,
         1.06718180e-321,  4.44659081e-323,  6.93496850e-310,
         6.93496104e-310,  0.00000000e+000,  1.97626258e-323,
         4.94065646e-324,  0.00000000e+000,  6.93489444e-310],
       [ 1.42290906e-321,  4.44659081e-323,  6.93496850e-310,
     

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
np.arange(15).reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
np.arange(15).reshape((1, 15))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [34]:
np.arange(15).reshape((15, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [35]:
np.arange(15).reshape((3, 4))

ValueError: cannot reshape array of size 15 into shape (3,4)

In [36]:
np.arange(1, 15, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [37]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.random.random((4, 5))

array([[0.29213497, 0.0172707 , 0.76800225, 0.7325933 , 0.41396906],
       [0.38851631, 0.50301522, 0.84059812, 0.65102604, 0.48350105],
       [0.7358468 , 0.69835701, 0.13512714, 0.36567737, 0.06881306],
       [0.63667016, 0.16416694, 0.5724624 , 0.26665057, 0.5450152 ]])

In [39]:
np.random.standard_normal((4, 5))

array([[ 0.876505  ,  1.53763588,  0.55386646, -1.91334306,  0.12810274],
       [ 1.7294123 ,  0.32998962, -0.32953604, -1.147443  ,  0.19672571],
       [ 0.55596624,  0.62031672, -2.26146443, -0.85269613, -0.57865789],
       [ 0.23961628,  0.69519807,  0.15990053,  1.01900085,  0.78845602]])

In [41]:
np.random.choice([1, 3, 7, 13], size=(4, 5))

array([[ 7,  1,  1,  1, 13],
       [13, 13, 13,  7,  1],
       [13,  3, 13,  1,  3],
       [ 7,  3,  1,  7, 13]])

In [44]:
np.mean(np.sum((np.random.random((100_000_000, 2)) ** 2), axis=1) < 1) * 4

3.14169056

In [48]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [1.0, 2.0, 3.0, 4.0]
])

In [49]:
arr.dtype

dtype('float64')

In [50]:
arr.itemsize

8

In [51]:
arr.size

8

In [52]:
arr.nbytes

64

In [53]:
arr.ndim

2

In [54]:
arr.shape

(2, 4)

In [55]:
arr.strides

(32, 8)

In [56]:
arr2 = arr.T

In [57]:
arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [58]:
arr2

array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.]])

In [61]:
arr[0, 0] = 99

In [62]:
arr

array([[99.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

In [63]:
arr2

array([[99.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.]])

In [64]:
id(arr), id(arr2)

(140365327795024, 140364509815072)

In [65]:
arr.strides

(32, 8)

In [66]:
arr2.strides

(8, 32)

In [67]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [68]:
arr2.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
arr.base is None

True

In [72]:
arr2.base is arr

True

In [73]:
i_arr = np.ones((3, 3), dtype=np.int8)

In [74]:
i_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [75]:
i_arr[0, 0] = 7

In [76]:
i_arr

array([[7, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [77]:
i_arr[0, 0] = 2020

In [78]:
i_arr

array([[-28,   1,   1],
       [  1,   1,   1],
       [  1,   1,   1]], dtype=int8)

In [79]:
i_arr = np.ones((3, 3), dtype=np.int64)

In [80]:
i_arr[0, 0]  = 1321893089021834

In [81]:
i_arr

array([[1321893089021834,                1,                1],
       [               1,                1,                1],
       [               1,                1,                1]])

In [82]:
cmpx = 1+1j

In [83]:
type(cmpx)

complex

In [85]:
cmplx = np.zeros((2, 3), dtype=np.complex128)

In [86]:
cmplx[0, 0] = 1+1j

In [87]:
cmplx

array([[1.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [88]:
vec = np.arange(5)

In [89]:
vec

array([0, 1, 2, 3, 4])

In [90]:
vec.shape

(5,)

In [91]:
m1 = vec.reshape((1, 5))

In [92]:
m1.shape

(1, 5)

In [93]:
m2 = vec.reshape((5, 1))

In [94]:
m2.shape

(5, 1)

In [95]:
vec

array([0, 1, 2, 3, 4])

In [96]:
m1

array([[0, 1, 2, 3, 4]])

In [97]:
m2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [98]:
arr7 = np.random.random((2, 3, 4))

In [99]:
arr7

array([[[0.92711651, 0.11094163, 0.18969629, 0.27351921],
        [0.39131438, 0.27242934, 0.0245779 , 0.16886894],
        [0.66516099, 0.34094283, 0.35414849, 0.18277568]],

       [[0.7641911 , 0.6654509 , 0.67763465, 0.258981  ],
        [0.77157326, 0.71451556, 0.69890118, 0.04450078],
        [0.87822473, 0.7114911 , 0.56043023, 0.91892352]]])

In [100]:
arr7.reshape((24,))

array([0.92711651, 0.11094163, 0.18969629, 0.27351921, 0.39131438,
       0.27242934, 0.0245779 , 0.16886894, 0.66516099, 0.34094283,
       0.35414849, 0.18277568, 0.7641911 , 0.6654509 , 0.67763465,
       0.258981  , 0.77157326, 0.71451556, 0.69890118, 0.04450078,
       0.87822473, 0.7114911 , 0.56043023, 0.91892352])

In [101]:
arr7.reshape((8, -1))

array([[0.92711651, 0.11094163, 0.18969629],
       [0.27351921, 0.39131438, 0.27242934],
       [0.0245779 , 0.16886894, 0.66516099],
       [0.34094283, 0.35414849, 0.18277568],
       [0.7641911 , 0.6654509 , 0.67763465],
       [0.258981  , 0.77157326, 0.71451556],
       [0.69890118, 0.04450078, 0.87822473],
       [0.7114911 , 0.56043023, 0.91892352]])

In [102]:
arr7.reshape((-1, 8))

array([[0.92711651, 0.11094163, 0.18969629, 0.27351921, 0.39131438,
        0.27242934, 0.0245779 , 0.16886894],
       [0.66516099, 0.34094283, 0.35414849, 0.18277568, 0.7641911 ,
        0.6654509 , 0.67763465, 0.258981  ],
       [0.77157326, 0.71451556, 0.69890118, 0.04450078, 0.87822473,
        0.7114911 , 0.56043023, 0.91892352]])

In [103]:
arr7.reshape((-1, 7))

ValueError: cannot reshape array of size 24 into shape (7)

In [104]:
vec

array([0, 1, 2, 3, 4])

In [105]:
vec.reshape((5, 1, 1))

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [108]:
vec[np.newaxis, :, np.newaxis]

array([[[0],
        [1],
        [2],
        [3],
        [4]]])

In [109]:
vec.reshape((1, -1, 1))

array([[[0],
        [1],
        [2],
        [3],
        [4]]])

In [110]:
vec[np.newaxis, :, np.newaxis, np.newaxis, np.newaxis]

array([[[[[0]]],


        [[[1]]],


        [[[2]]],


        [[[3]]],


        [[[4]]]]])

In [119]:
a = np.arange(5)

In [121]:
b = np.arange(5) * 100

In [122]:
a

array([0, 1, 2, 3, 4])

In [123]:
b

array([  0, 100, 200, 300, 400])

In [124]:
np.concatenate((a, b))

array([  0,   1,   2,   3,   4,   0, 100, 200, 300, 400])

In [125]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[  0,   1,   2,   3,   4],
       [  0, 100, 200, 300, 400]])

In [127]:
c = np.stack((a, b))

In [128]:
c

array([[  0,   1,   2,   3,   4],
       [  0, 100, 200, 300, 400]])

In [130]:
np.split(c, (1, 3), axis=1)

[array([[0],
        [0]]),
 array([[  1,   2],
        [100, 200]]),
 array([[  3,   4],
        [300, 400]])]

In [132]:
np.sum(c, axis=0)

array([  0, 101, 202, 303, 404])

In [133]:
np.sum(c, axis=1)

array([  10, 1000])

In [139]:
arr = np.arange(60).reshape((10, 6))

In [140]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [142]:
arr[0:3, 3]

array([ 3,  9, 15])

In [143]:
arr[0:10:2, 4]

array([ 4, 16, 28, 40, 52])

In [144]:
arr[::2, ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28],
       [36, 38, 40],
       [48, 50, 52]])

In [145]:
arr2 = arr[::2, ::2]

In [146]:
arr2.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [147]:
arr2.strides

(96, 16)

In [148]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [150]:
arr[:, 1]

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55])

In [151]:
arr = np.random.standard_normal((8, 8))

In [152]:
arr

array([[-0.24328692, -0.38309847, -0.16104147,  1.39815953,  1.60144641,
        -0.97496019, -0.71932549,  1.7049646 ],
       [-1.67255125,  1.27657746,  0.9748509 , -1.17948254,  0.74230738,
         1.28728995, -1.07591637,  0.4781963 ],
       [ 1.00506721, -0.78678244,  0.95274494,  0.92740651, -0.99313811,
         1.20964068, -1.59007948,  1.86265617],
       [ 1.24647048, -0.76646577,  0.69511585, -1.02854508, -1.0790916 ,
        -0.12604061, -1.14069101, -0.47513884],
       [ 0.31005705, -0.42374616,  1.64224098,  0.39008488, -0.9165779 ,
         0.37290277, -2.35789824,  1.05958989],
       [ 0.73801906,  0.45495389,  0.49356027, -1.04643116, -0.85698955,
        -0.70133566, -0.1900579 , -0.49134038],
       [-1.51012324,  0.94084919, -0.41354443,  1.61912839,  1.25292268,
         0.16490734,  0.93746274,  0.58356859],
       [ 1.09351298,  0.09537923, -0.20816992, -0.0678147 ,  0.71842783,
        -2.61005631,  1.37251052, -1.21012593]])

In [153]:
arr * 1000

array([[ -243.28692028,  -383.09847312,  -161.04146568,  1398.159527  ,
         1601.44640979,  -974.96019372,  -719.32549344,  1704.96460087],
       [-1672.55124553,  1276.57746227,   974.85089779, -1179.48254018,
          742.30738053,  1287.28995122, -1075.9163655 ,   478.19630416],
       [ 1005.06721332,  -786.78243554,   952.74493657,   927.4065143 ,
         -993.13811225,  1209.64068041, -1590.07947773,  1862.6561675 ],
       [ 1246.47048485,  -766.46577135,   695.11584986, -1028.54508154,
        -1079.09160091,  -126.04060954, -1140.69100617,  -475.13883822],
       [  310.05704548,  -423.7461599 ,  1642.24097575,   390.08488079,
         -916.57789682,   372.90277389, -2357.89824244,  1059.58988874],
       [  738.01906461,   454.95388874,   493.5602728 , -1046.43115541,
         -856.98954627,  -701.33565803,  -190.05790199,  -491.34037988],
       [-1510.12324379,   940.8491922 ,  -413.54443184,  1619.12839206,
         1252.92268272,   164.90733877,   937.46273933,   

In [154]:
arr > 0

array([[False, False, False,  True,  True, False, False,  True],
       [False,  True,  True, False,  True,  True, False,  True],
       [ True, False,  True,  True, False,  True, False,  True],
       [ True, False,  True, False, False, False, False, False],
       [ True, False,  True,  True, False,  True, False,  True],
       [ True,  True,  True, False, False, False, False, False],
       [False,  True, False,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True, False,  True, False]])

In [156]:
arr[arr < 0] = 0.0

In [157]:
arr

array([[0.        , 0.        , 0.        , 1.39815953, 1.60144641,
        0.        , 0.        , 1.7049646 ],
       [0.        , 1.27657746, 0.9748509 , 0.        , 0.74230738,
        1.28728995, 0.        , 0.4781963 ],
       [1.00506721, 0.        , 0.95274494, 0.92740651, 0.        ,
        1.20964068, 0.        , 1.86265617],
       [1.24647048, 0.        , 0.69511585, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.31005705, 0.        , 1.64224098, 0.39008488, 0.        ,
        0.37290277, 0.        , 1.05958989],
       [0.73801906, 0.45495389, 0.49356027, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.94084919, 0.        , 1.61912839, 1.25292268,
        0.16490734, 0.93746274, 0.58356859],
       [1.09351298, 0.09537923, 0.        , 0.        , 0.71842783,
        0.        , 1.37251052, 0.        ]])

In [158]:
arr

array([[0.        , 0.        , 0.        , 1.39815953, 1.60144641,
        0.        , 0.        , 1.7049646 ],
       [0.        , 1.27657746, 0.9748509 , 0.        , 0.74230738,
        1.28728995, 0.        , 0.4781963 ],
       [1.00506721, 0.        , 0.95274494, 0.92740651, 0.        ,
        1.20964068, 0.        , 1.86265617],
       [1.24647048, 0.        , 0.69511585, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.31005705, 0.        , 1.64224098, 0.39008488, 0.        ,
        0.37290277, 0.        , 1.05958989],
       [0.73801906, 0.45495389, 0.49356027, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.94084919, 0.        , 1.61912839, 1.25292268,
        0.16490734, 0.93746274, 0.58356859],
       [1.09351298, 0.09537923, 0.        , 0.        , 0.71842783,
        0.        , 1.37251052, 0.        ]])

In [160]:
arr = np.arange(60).reshape((10, -1))

In [161]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [164]:
arr[:, [1, 0, 1, 2, 0]]

array([[ 1,  0,  1,  2,  0],
       [ 7,  6,  7,  8,  6],
       [13, 12, 13, 14, 12],
       [19, 18, 19, 20, 18],
       [25, 24, 25, 26, 24],
       [31, 30, 31, 32, 30],
       [37, 36, 37, 38, 36],
       [43, 42, 43, 44, 42],
       [49, 48, 49, 50, 48],
       [55, 54, 55, 56, 54]])

In [165]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [166]:
arr.sum()

1770

In [167]:
arr.sum(axis=0)

array([270, 280, 290, 300, 310, 320])

In [168]:
arr.sum(axis=1)

array([ 15,  51,  87, 123, 159, 195, 231, 267, 303, 339])

In [169]:
arr.min(axis=1)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [170]:
arr.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [175]:
np.unravel_index(arr.argmax(axis=1), arr.shape)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [176]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [177]:
arr * 1000

array([[    0,  1000,  2000,  3000,  4000,  5000],
       [ 6000,  7000,  8000,  9000, 10000, 11000],
       [12000, 13000, 14000, 15000, 16000, 17000],
       [18000, 19000, 20000, 21000, 22000, 23000],
       [24000, 25000, 26000, 27000, 28000, 29000],
       [30000, 31000, 32000, 33000, 34000, 35000],
       [36000, 37000, 38000, 39000, 40000, 41000],
       [42000, 43000, 44000, 45000, 46000, 47000],
       [48000, 49000, 50000, 51000, 52000, 53000],
       [54000, 55000, 56000, 57000, 58000, 59000]])

In [178]:
arr + arr

array([[  0,   2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20,  22],
       [ 24,  26,  28,  30,  32,  34],
       [ 36,  38,  40,  42,  44,  46],
       [ 48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80,  82],
       [ 84,  86,  88,  90,  92,  94],
       [ 96,  98, 100, 102, 104, 106],
       [108, 110, 112, 114, 116, 118]])

In [180]:
arr + np.arange(6)

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16],
       [12, 14, 16, 18, 20, 22],
       [18, 20, 22, 24, 26, 28],
       [24, 26, 28, 30, 32, 34],
       [30, 32, 34, 36, 38, 40],
       [36, 38, 40, 42, 44, 46],
       [42, 44, 46, 48, 50, 52],
       [48, 50, 52, 54, 56, 58],
       [54, 56, 58, 60, 62, 64]])

In [181]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [182]:
orig = np.ones((5, 3, 8))

In [183]:
orig

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [184]:
orig + np.arange(8)

array([[[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]],

       [[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]],

       [[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]],

       [[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]],

       [[1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8.]]])

In [188]:
orig + np.arange(5)[:, np.newaxis, np.newaxis]

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]]])

In [189]:
vec

array([0, 1, 2, 3, 4])

In [194]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [198]:
arr.sum(axis=1)

array([ 15,  51,  87, 123, 159, 195, 231, 267, 303, 339])

In [202]:
np.arange(28).reshape((4, -1)).shape

(4, 7)

In [204]:
arr.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5, 32.5, 38.5, 44.5, 50.5, 56.5])

In [205]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])